const UPDATE_INTERVAL = 30;
const GET_INTERVAL = 30;
const DISTANCE_INTERVAL = 100;
const UPDATE_INTERVAL_KEY = "updateInterval";
const DISTANCE_INTERVAL_KEY = "distanceInterval";

export {
  DISTANCE_INTERVAL,
  DISTANCE_INTERVAL_KEY,
  GET_INTERVAL,
  UPDATE_INTERVAL,
  UPDATE_INTERVAL_KEY,
};
